add missing include
move <QElapsedTimer> in header

>In file included from ui_modules/mathmod.h:25,
>                 from ui_modules/drawingoptions.h:27:
>ui_modules/../pariso/isosurface/Iso3D.h:119:5: error: ‘QElapsedTimer’ does not name a type; did you mean ‘QBasicTimer’?
>  119 |     QElapsedTimer times;
>      |     ^~~~~~~~~~~~~
>      |     QBasicTimer

Signed-off-by: Nicolas PARLANT <nicolas.parlant@parhuet.fr>