fix compile with c++20
>from ui_modules/mathmod.cpp:20:
>/usr/lib/gcc/x86_64-pc-linux-gnu/16/include/g++-v16/math.h:183:12:
>error: constexpr float std::lerp(float, float, float)
>conflicts with a previous declaration
>  183 | using std::lerp;

lerp is declared globally with c++20 which is by default with gcc-16 and
allowed by qt-6.10

Signed-off-by: Nicolas PARLANT <nicolas.parlant@parhuet.fr>